-- Tabela zgłoszeń telefonicznych z landing /znajdz
-- Wykonaj w Supabase SQL Editor (projekt ofrgucsumxydrkwvtrik)

create table if not exists public.phone_leads (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  phone       text not null,
  relation    text,
  age_range   text,
  needs       text[],
  other_need  text,
  city        text,
  source      text
);

alter table public.phone_leads enable row level security;

-- pozwól KAŻDEMU (także anon) wstawić wiersz
create policy "anon can insert phone_leads"
  on public.phone_leads for insert
  to anon
  with check (true);

-- (celowo NIE dodajemy policy SELECT — nikt anonimowy nie odczyta listy)
